import { axiosInstance } from "../utils/axiosTypes"

export const IS_LOGGING_IN="IS_LOGGING_IN"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_ERROR="LOGIN_ERROR"
export const IS_LOGGING_OUT="IS_LOGGING_IN"
export const LOGOUT_SUCCESS="LOGIN_SUCCESS"
export const LOGOUT_ERROR="LOGIN_ERROR"
export const IS_SIGNING_UP="IS_SIGNING_UP"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_ERROR="SIGNUP_ERROR"