export const GETTING_EVENT="GETTING_EVENT"
export const GOT_EVENT='GOT_EVENT'
export const GOT_EVENT_ERROR='GOT_EVENT_ERROR'

export const ADDING_GUESTS="ADDING_GUESTS"
export const ADDED_GUESTS='ADDED_GUESTS'
export const ADD_GUESTS_ERROR="ADD_GUESTS_ERROR"

export const ADDING_RECIPES="ADDING_RECIPES"
export const ADDED_RECIPES="ADDED_RECIPES"
export const ADD_RECIPES_ERROR="ADD_RECIPES_ERROR"