export { loginReducer } from './loginReducer'
export { eventReducer } from './eventReducer'
export { dataReducer } from './dataReducer'
export { signUpReducer } from './signUpReducer'
export { usersReducer } from './usersReducer'
